#!/usr/bin/env sh

jobs=1
if [ -n "$1" ]; then jobs=$1; fi

if [ -f /proc/cpuinfo ]
then
    jobs=`cat /proc/cpuinfo | grep processor | wc -l`
fi

cppcheck -j $jobs --enable=all -f \
-I cegui/include cegui/ 2> cppcheck-output

