// This file has been generated by Py++.

#ifndef SingletonMouseCursor_hpp__pyplusplus_wrapper
#define SingletonMouseCursor_hpp__pyplusplus_wrapper

void register_SingletonMouseCursor_class();

#endif//SingletonMouseCursor_hpp__pyplusplus_wrapper
