// This file has been generated by Py++.

#ifndef BiDiVisualMapping_hpp__pyplusplus_wrapper
#define BiDiVisualMapping_hpp__pyplusplus_wrapper

void register_BiDiVisualMapping_class();

#endif//BiDiVisualMapping_hpp__pyplusplus_wrapper
