// This file has been generated by Py++.

#include "boost/python.hpp"
#include "python_CEGUI.h"
#include "FontDim.pypp.hpp"

namespace bp = boost::python;

struct FontDim_wrapper : CEGUI::FontDim, bp::wrapper< CEGUI::FontDim > {

    FontDim_wrapper(CEGUI::FontDim const & arg )
    : CEGUI::FontDim( arg )
      , bp::wrapper< CEGUI::FontDim >(){
        // copy constructor
        
    }

    FontDim_wrapper(::CEGUI::String const & name, ::CEGUI::String const & font, ::CEGUI::String const & text, ::CEGUI::FontMetricType metric, float padding=0 )
    : CEGUI::FontDim( boost::ref(name), boost::ref(font), boost::ref(text), metric, padding )
      , bp::wrapper< CEGUI::FontDim >(){
        // constructor
    
    }

    virtual ::CEGUI::BaseDim * clone_impl(  ) const {
        if( bp::override func_clone_impl = this->get_override( "clone_impl" ) )
            return func_clone_impl(  );
        else{
            return this->CEGUI::FontDim::clone_impl(  );
        }
    }
    
    virtual ::CEGUI::BaseDim * default_clone_impl(  ) const {
        return CEGUI::FontDim::clone_impl( );
    }

    virtual float getValue_impl( ::CEGUI::Window const & wnd ) const {
        if( bp::override func_getValue_impl = this->get_override( "getValue_impl" ) )
            return func_getValue_impl( boost::ref(wnd) );
        else{
            return this->CEGUI::FontDim::getValue_impl( boost::ref(wnd) );
        }
    }
    
    virtual float default_getValue_impl( ::CEGUI::Window const & wnd ) const {
        return CEGUI::FontDim::getValue_impl( boost::ref(wnd) );
    }

    virtual float getValue_impl( ::CEGUI::Window const & wnd, ::CEGUI::Rectf const & container ) const {
        if( bp::override func_getValue_impl = this->get_override( "getValue_impl" ) )
            return func_getValue_impl( boost::ref(wnd), boost::ref(container) );
        else{
            return this->CEGUI::FontDim::getValue_impl( boost::ref(wnd), boost::ref(container) );
        }
    }
    
    virtual float default_getValue_impl( ::CEGUI::Window const & wnd, ::CEGUI::Rectf const & container ) const {
        return CEGUI::FontDim::getValue_impl( boost::ref(wnd), boost::ref(container) );
    }

    virtual void writeXMLElementAttributes_impl( ::CEGUI::XMLSerializer & xml_stream ) const {
        if( bp::override func_writeXMLElementAttributes_impl = this->get_override( "writeXMLElementAttributes_impl" ) )
            func_writeXMLElementAttributes_impl( boost::ref(xml_stream) );
        else{
            this->CEGUI::FontDim::writeXMLElementAttributes_impl( boost::ref(xml_stream) );
        }
    }
    
    virtual void default_writeXMLElementAttributes_impl( ::CEGUI::XMLSerializer & xml_stream ) const {
        CEGUI::FontDim::writeXMLElementAttributes_impl( boost::ref(xml_stream) );
    }

    virtual void writeXMLElementName_impl( ::CEGUI::XMLSerializer & xml_stream ) const {
        if( bp::override func_writeXMLElementName_impl = this->get_override( "writeXMLElementName_impl" ) )
            func_writeXMLElementName_impl( boost::ref(xml_stream) );
        else{
            this->CEGUI::FontDim::writeXMLElementName_impl( boost::ref(xml_stream) );
        }
    }
    
    virtual void default_writeXMLElementName_impl( ::CEGUI::XMLSerializer & xml_stream ) const {
        CEGUI::FontDim::writeXMLElementName_impl( boost::ref(xml_stream) );
    }

};

void register_FontDim_class(){

    { //::CEGUI::FontDim
        typedef bp::class_< FontDim_wrapper, bp::bases< CEGUI::BaseDim > > FontDim_exposer_t;
        FontDim_exposer_t FontDim_exposer = FontDim_exposer_t( "FontDim", "*!\n\
        \n\
            Dimension type that represents some metric of a Font.  Implements BaseDim interface.\n\
        *\n", bp::init< CEGUI::String const &, CEGUI::String const &, CEGUI::String const &, CEGUI::FontMetricType, bp::optional< float > >(( bp::arg("name"), bp::arg("font"), bp::arg("text"), bp::arg("metric"), bp::arg("padding")=0 ), "*!\n\
                \n\
                    Constructor.\n\
        \n\
                @param name\n\
                    String holding the name suffix of the window to be accessed to obtain the font\n\
                    and  or text strings to be used when these items are not explicitly given.\n\
        \n\
                @param font\n\
                    String holding the name of the font to use for this dimension.  If the string is\n\
                    empty, the font assigned to the window passed to getValue will be used.\n\
        \n\
                @param text\n\
                    String holding the text to be measured for horizontal extent.  If this is empty,\n\
                    the text from the window passed to getValue will be used.\n\
        \n\
                @param metric\n\
                    One of the FontMetricType values indicating what we should represent.\n\
        \n\
                @param padding\n\
                    constant pixel padding value to be added.\n\
                *\n") );
        bp::scope FontDim_scope( FontDim_exposer );
        { //::CEGUI::FontDim::clone_impl
        
            typedef ::CEGUI::BaseDim * ( FontDim_wrapper::*clone_impl_function_type )(  ) const;
            
            FontDim_exposer.def( 
                "clone_impl"
                , clone_impl_function_type( &FontDim_wrapper::default_clone_impl )
                , bp::return_value_policy< bp::reference_existing_object >() );
        
        }
        { //::CEGUI::FontDim::getValue_impl
        
            typedef float ( FontDim_wrapper::*getValue_impl_function_type )( ::CEGUI::Window const & ) const;
            
            FontDim_exposer.def( 
                "getValue_impl"
                , getValue_impl_function_type( &FontDim_wrapper::default_getValue_impl )
                , ( bp::arg("wnd") )
                , "Implementation of the base class interface\n" );
        
        }
        { //::CEGUI::FontDim::getValue_impl
        
            typedef float ( FontDim_wrapper::*getValue_impl_function_type )( ::CEGUI::Window const &,::CEGUI::Rectf const & ) const;
            
            FontDim_exposer.def( 
                "getValue_impl"
                , getValue_impl_function_type( &FontDim_wrapper::default_getValue_impl )
                , ( bp::arg("wnd"), bp::arg("container") )
                , "Implementation of the base class interface\n" );
        
        }
        { //::CEGUI::FontDim::writeXMLElementAttributes_impl
        
            typedef void ( FontDim_wrapper::*writeXMLElementAttributes_impl_function_type )( ::CEGUI::XMLSerializer & ) const;
            
            FontDim_exposer.def( 
                "writeXMLElementAttributes_impl"
                , writeXMLElementAttributes_impl_function_type( &FontDim_wrapper::default_writeXMLElementAttributes_impl )
                , ( bp::arg("xml_stream") ) );
        
        }
        { //::CEGUI::FontDim::writeXMLElementName_impl
        
            typedef void ( FontDim_wrapper::*writeXMLElementName_impl_function_type )( ::CEGUI::XMLSerializer & ) const;
            
            FontDim_exposer.def( 
                "writeXMLElementName_impl"
                , writeXMLElementName_impl_function_type( &FontDim_wrapper::default_writeXMLElementName_impl )
                , ( bp::arg("xml_stream") ) );
        
        }
    }

}
