// This file has been generated by Py++.

#include "boost/python.hpp"
#include "python_CEGUI.h"
#include "ImageDim.pypp.hpp"

namespace bp = boost::python;

void register_ImageDim_class(){

    { //::CEGUI::ImageDim
        typedef bp::class_< CEGUI::ImageDim, bp::bases< CEGUI::BaseDim > > ImageDim_exposer_t;
        ImageDim_exposer_t ImageDim_exposer = ImageDim_exposer_t( "ImageDim", "*!\n\
        \n\
            Dimension type that represents some dimension of a named Image.  Implements BaseDim interface.\n\
        *\n", bp::init< CEGUI::String const &, CEGUI::DimensionType >(( bp::arg("name"), bp::arg("dim") ), "*!\n\
                \n\
                    Constructor.\n\
        \n\
                @param name\n\
                    String object holding the name of the image.\n\
        \n\
                @param dim\n\
                    DimensionType value indicating which dimension of the described image that this\
                    ImageDim\n\
                    is to represent.\n\
                *\n") );
        bp::scope ImageDim_scope( ImageDim_exposer );
        { //::CEGUI::ImageDim::setSourceDimension
        
            typedef void ( ::CEGUI::ImageDim::*setSourceDimension_function_type )( ::CEGUI::DimensionType ) ;
            
            ImageDim_exposer.def( 
                "setSourceDimension"
                , setSourceDimension_function_type( &::CEGUI::ImageDim::setSourceDimension )
                , ( bp::arg("dim") )
                , "*!\n\
                    \n\
                        Sets the source dimension type for this ImageDim.\n\
            \n\
                    @param dim\n\
                        DimensionType value indicating which dimension of the described image that this\
                        ImageDim\n\
                        is to represent.\n\
            \n\
                    @return\n\
                        Nothing.\n\
                    *\n" );
        
        }
        { //::CEGUI::ImageDim::setSourceImage
        
            typedef void ( ::CEGUI::ImageDim::*setSourceImage_function_type )( ::CEGUI::String const & ) ;
            
            ImageDim_exposer.def( 
                "setSourceImage"
                , setSourceImage_function_type( &::CEGUI::ImageDim::setSourceImage )
                , ( bp::arg("name") )
                , "*!\n\
                    \n\
                        Sets the source image information for this ImageDim.\n\
            \n\
                    @param name\n\
                        String object holding the name of the image.\n\
            \n\
                    @return\n\
                        Nothing.\n\
                    *\n" );
        
        }
    }

}
