// This file has been generated by Py++.

#include "boost/python.hpp"
#include "python_CEGUI.h"
#include "NamedXMLResourceManagerImageset.pypp.hpp"

namespace bp = boost::python;

struct NamedXMLResourceManager_less__CEGUI_scope_Imageset_comma__CEGUI_scope_Imageset_xmlHandler__greater__wrapper : CEGUI::NamedXMLResourceManager< CEGUI::Imageset, CEGUI::Imageset_xmlHandler >, bp::wrapper< CEGUI::NamedXMLResourceManager< CEGUI::Imageset, CEGUI::Imageset_xmlHandler > > {

    NamedXMLResourceManager_less__CEGUI_scope_Imageset_comma__CEGUI_scope_Imageset_xmlHandler__greater__wrapper(::CEGUI::String const & resource_type )
    : CEGUI::NamedXMLResourceManager<CEGUI::Imageset, CEGUI::Imageset_xmlHandler>( boost::ref(resource_type) )
      , bp::wrapper< CEGUI::NamedXMLResourceManager< CEGUI::Imageset, CEGUI::Imageset_xmlHandler > >(){
        // constructor
    
    }

    virtual void fireEvent( ::CEGUI::String const & name, ::CEGUI::EventArgs & args, ::CEGUI::String const & eventNamespace="" ) {
        if( bp::override func_fireEvent = this->get_override( "fireEvent" ) )
            func_fireEvent( boost::ref(name), boost::ref(args), boost::ref(eventNamespace) );
        else{
            this->CEGUI::EventSet::fireEvent( boost::ref(name), boost::ref(args), boost::ref(eventNamespace) );
        }
    }
    
    void default_fireEvent( ::CEGUI::String const & name, ::CEGUI::EventArgs & args, ::CEGUI::String const & eventNamespace="" ) {
        CEGUI::EventSet::fireEvent( boost::ref(name), boost::ref(args), boost::ref(eventNamespace) );
    }

    virtual ::CEGUI::RefCounted< CEGUI::BoundSlot > subscribeScriptedEvent( ::CEGUI::String const & name, ::CEGUI::String const & subscriber_name ) {
        if( bp::override func_subscribeScriptedEvent = this->get_override( "subscribeScriptedEvent" ) )
            return func_subscribeScriptedEvent( boost::ref(name), boost::ref(subscriber_name) );
        else{
            return this->CEGUI::EventSet::subscribeScriptedEvent( boost::ref(name), boost::ref(subscriber_name) );
        }
    }
    
    ::CEGUI::RefCounted< CEGUI::BoundSlot > default_subscribeScriptedEvent( ::CEGUI::String const & name, ::CEGUI::String const & subscriber_name ) {
        return CEGUI::EventSet::subscribeScriptedEvent( boost::ref(name), boost::ref(subscriber_name) );
    }

    virtual ::CEGUI::RefCounted< CEGUI::BoundSlot > subscribeScriptedEvent( ::CEGUI::String const & name, unsigned int group, ::CEGUI::String const & subscriber_name ) {
        if( bp::override func_subscribeScriptedEvent = this->get_override( "subscribeScriptedEvent" ) )
            return func_subscribeScriptedEvent( boost::ref(name), group, boost::ref(subscriber_name) );
        else{
            return this->CEGUI::EventSet::subscribeScriptedEvent( boost::ref(name), group, boost::ref(subscriber_name) );
        }
    }
    
    ::CEGUI::RefCounted< CEGUI::BoundSlot > default_subscribeScriptedEvent( ::CEGUI::String const & name, unsigned int group, ::CEGUI::String const & subscriber_name ) {
        return CEGUI::EventSet::subscribeScriptedEvent( boost::ref(name), group, boost::ref(subscriber_name) );
    }

};

void register_NamedXMLResourceManagerImageset_class(){

    { //::CEGUI::NamedXMLResourceManager< CEGUI::Imageset, CEGUI::Imageset_xmlHandler >
        typedef bp::class_< NamedXMLResourceManager_less__CEGUI_scope_Imageset_comma__CEGUI_scope_Imageset_xmlHandler__greater__wrapper, bp::bases< CEGUI::ResourceEventSet >, boost::noncopyable > NamedXMLResourceManagerImageset_exposer_t;
        NamedXMLResourceManagerImageset_exposer_t NamedXMLResourceManagerImageset_exposer = NamedXMLResourceManagerImageset_exposer_t( "NamedXMLResourceManagerImageset", bp::init< CEGUI::String const & >(( bp::arg("resource_type") )) );
        bp::scope NamedXMLResourceManagerImageset_scope( NamedXMLResourceManagerImageset_exposer );
        bp::implicitly_convertible< CEGUI::String const &, CEGUI::NamedXMLResourceManager< CEGUI::Imageset, CEGUI::Imageset_xmlHandler > >();
        { //::CEGUI::NamedXMLResourceManager< CEGUI::Imageset, CEGUI::Imageset_xmlHandler >::create
        
            typedef CEGUI::NamedXMLResourceManager< CEGUI::Imageset, CEGUI::Imageset_xmlHandler > exported_class_t;
            typedef ::CEGUI::Imageset & ( exported_class_t::*create_function_type )( ::CEGUI::String const &,::CEGUI::String const &,::CEGUI::XMLResourceExistsAction ) ;
            
            NamedXMLResourceManagerImageset_exposer.def( 
                "create"
                , create_function_type( &::CEGUI::NamedXMLResourceManager< CEGUI::Imageset, CEGUI::Imageset_xmlHandler >::create )
                , ( bp::arg("xml_filename"), bp::arg("resource_group")="", bp::arg("action")=CEGUI::XREA_RETURN )
                , bp::return_value_policy< bp::reference_existing_object >() );
        
        }
        { //::CEGUI::NamedXMLResourceManager< CEGUI::Imageset, CEGUI::Imageset_xmlHandler >::createAll
        
            typedef CEGUI::NamedXMLResourceManager< CEGUI::Imageset, CEGUI::Imageset_xmlHandler > exported_class_t;
            typedef void ( exported_class_t::*createAll_function_type )( ::CEGUI::String const &,::CEGUI::String const & ) ;
            
            NamedXMLResourceManagerImageset_exposer.def( 
                "createAll"
                , createAll_function_type( &::CEGUI::NamedXMLResourceManager< CEGUI::Imageset, CEGUI::Imageset_xmlHandler >::createAll )
                , ( bp::arg("pattern"), bp::arg("resource_group") ) );
        
        }
        { //::CEGUI::NamedXMLResourceManager< CEGUI::Imageset, CEGUI::Imageset_xmlHandler >::destroy
        
            typedef CEGUI::NamedXMLResourceManager< CEGUI::Imageset, CEGUI::Imageset_xmlHandler > exported_class_t;
            typedef void ( exported_class_t::*destroy_function_type )( ::CEGUI::String const & ) ;
            
            NamedXMLResourceManagerImageset_exposer.def( 
                "destroy"
                , destroy_function_type( &::CEGUI::NamedXMLResourceManager< CEGUI::Imageset, CEGUI::Imageset_xmlHandler >::destroy )
                , ( bp::arg("object_name") )
                , "----------------------------------------------------------------------------\n" );
        
        }
        { //::CEGUI::NamedXMLResourceManager< CEGUI::Imageset, CEGUI::Imageset_xmlHandler >::destroy
        
            typedef CEGUI::NamedXMLResourceManager< CEGUI::Imageset, CEGUI::Imageset_xmlHandler > exported_class_t;
            typedef void ( exported_class_t::*destroy_function_type )( ::CEGUI::Imageset const & ) ;
            
            NamedXMLResourceManagerImageset_exposer.def( 
                "destroy"
                , destroy_function_type( &::CEGUI::NamedXMLResourceManager< CEGUI::Imageset, CEGUI::Imageset_xmlHandler >::destroy )
                , ( bp::arg("object") )
                , "----------------------------------------------------------------------------\n" );
        
        }
        { //::CEGUI::NamedXMLResourceManager< CEGUI::Imageset, CEGUI::Imageset_xmlHandler >::destroyAll
        
            typedef CEGUI::NamedXMLResourceManager< CEGUI::Imageset, CEGUI::Imageset_xmlHandler > exported_class_t;
            typedef void ( exported_class_t::*destroyAll_function_type )(  ) ;
            
            NamedXMLResourceManagerImageset_exposer.def( 
                "destroyAll"
                , destroyAll_function_type( &::CEGUI::NamedXMLResourceManager< CEGUI::Imageset, CEGUI::Imageset_xmlHandler >::destroyAll )
                , "----------------------------------------------------------------------------\n" );
        
        }
        { //::CEGUI::NamedXMLResourceManager< CEGUI::Imageset, CEGUI::Imageset_xmlHandler >::get
        
            typedef CEGUI::NamedXMLResourceManager< CEGUI::Imageset, CEGUI::Imageset_xmlHandler > exported_class_t;
            typedef ::CEGUI::Imageset & ( exported_class_t::*get_function_type )( ::CEGUI::String const & ) const;
            
            NamedXMLResourceManagerImageset_exposer.def( 
                "get"
                , get_function_type( &::CEGUI::NamedXMLResourceManager< CEGUI::Imageset, CEGUI::Imageset_xmlHandler >::get )
                , ( bp::arg("object_name") )
                , bp::return_value_policy< bp::reference_existing_object >()
                , "----------------------------------------------------------------------------\n" );
        
        }
        { //::CEGUI::NamedXMLResourceManager< CEGUI::Imageset, CEGUI::Imageset_xmlHandler >::isDefined
        
            typedef CEGUI::NamedXMLResourceManager< CEGUI::Imageset, CEGUI::Imageset_xmlHandler > exported_class_t;
            typedef bool ( exported_class_t::*isDefined_function_type )( ::CEGUI::String const & ) const;
            
            NamedXMLResourceManagerImageset_exposer.def( 
                "isDefined"
                , isDefined_function_type( &::CEGUI::NamedXMLResourceManager< CEGUI::Imageset, CEGUI::Imageset_xmlHandler >::isDefined )
                , ( bp::arg("object_name") )
                , "----------------------------------------------------------------------------\n" );
        
        }
        { //::CEGUI::EventSet::fireEvent
        
            typedef void ( ::CEGUI::EventSet::*fireEvent_function_type )( ::CEGUI::String const &,::CEGUI::EventArgs &,::CEGUI::String const & ) ;
            typedef void ( NamedXMLResourceManager_less__CEGUI_scope_Imageset_comma__CEGUI_scope_Imageset_xmlHandler__greater__wrapper::*default_fireEvent_function_type )( ::CEGUI::String const &,::CEGUI::EventArgs &,::CEGUI::String const & ) ;
            
            NamedXMLResourceManagerImageset_exposer.def( 
                "fireEvent"
                , fireEvent_function_type(&::CEGUI::EventSet::fireEvent)
                , default_fireEvent_function_type(&NamedXMLResourceManager_less__CEGUI_scope_Imageset_comma__CEGUI_scope_Imageset_xmlHandler__greater__wrapper::default_fireEvent)
                , ( bp::arg("name"), bp::arg("args"), bp::arg("eventNamespace")="" ) );
        
        }
        { //::CEGUI::EventSet::subscribeScriptedEvent
        
            typedef ::CEGUI::RefCounted< CEGUI::BoundSlot > ( ::CEGUI::EventSet::*subscribeScriptedEvent_function_type )( ::CEGUI::String const &,::CEGUI::String const & ) ;
            typedef ::CEGUI::RefCounted< CEGUI::BoundSlot > ( NamedXMLResourceManager_less__CEGUI_scope_Imageset_comma__CEGUI_scope_Imageset_xmlHandler__greater__wrapper::*default_subscribeScriptedEvent_function_type )( ::CEGUI::String const &,::CEGUI::String const & ) ;
            
            NamedXMLResourceManagerImageset_exposer.def( 
                "subscribeScriptedEvent"
                , subscribeScriptedEvent_function_type(&::CEGUI::EventSet::subscribeScriptedEvent)
                , default_subscribeScriptedEvent_function_type(&NamedXMLResourceManager_less__CEGUI_scope_Imageset_comma__CEGUI_scope_Imageset_xmlHandler__greater__wrapper::default_subscribeScriptedEvent)
                , ( bp::arg("name"), bp::arg("subscriber_name") ) );
        
        }
        { //::CEGUI::EventSet::subscribeScriptedEvent
        
            typedef ::CEGUI::RefCounted< CEGUI::BoundSlot > ( ::CEGUI::EventSet::*subscribeScriptedEvent_function_type )( ::CEGUI::String const &,unsigned int,::CEGUI::String const & ) ;
            typedef ::CEGUI::RefCounted< CEGUI::BoundSlot > ( NamedXMLResourceManager_less__CEGUI_scope_Imageset_comma__CEGUI_scope_Imageset_xmlHandler__greater__wrapper::*default_subscribeScriptedEvent_function_type )( ::CEGUI::String const &,unsigned int,::CEGUI::String const & ) ;
            
            NamedXMLResourceManagerImageset_exposer.def( 
                "subscribeScriptedEvent"
                , subscribeScriptedEvent_function_type(&::CEGUI::EventSet::subscribeScriptedEvent)
                , default_subscribeScriptedEvent_function_type(&NamedXMLResourceManager_less__CEGUI_scope_Imageset_comma__CEGUI_scope_Imageset_xmlHandler__greater__wrapper::default_subscribeScriptedEvent)
                , ( bp::arg("name"), bp::arg("group"), bp::arg("subscriber_name") ) );
        
        }
    }

}
