// This file has been generated by Py++.

#ifndef PropertyDefinition_hpp__pyplusplus_wrapper
#define PropertyDefinition_hpp__pyplusplus_wrapper

void register_PropertyDefinition_class();

#endif//PropertyDefinition_hpp__pyplusplus_wrapper
