// This file has been generated by Py++.

#ifndef PropertyLinkDefinition_hpp__pyplusplus_wrapper
#define PropertyLinkDefinition_hpp__pyplusplus_wrapper

void register_PropertyLinkDefinition_class();

#endif//PropertyLinkDefinition_hpp__pyplusplus_wrapper
