// This file has been generated by Py++.

#include "boost/python.hpp"
#include "python_CEGUI.h"
#include "Sizef.pypp.hpp"

namespace bp = boost::python;

void register_Sizef_class(){

    { //::CEGUI::Size< float >
        typedef bp::class_< CEGUI::Size< float > > Sizef_exposer_t;
        Sizef_exposer_t Sizef_exposer = Sizef_exposer_t( "Sizef", bp::init< >() );
        bp::scope Sizef_scope( Sizef_exposer );
        Sizef_exposer.def( bp::init< float const &, float const & >(( bp::arg("width"), bp::arg("height") )) );
        Sizef_exposer.def( bp::init< CEGUI::Size< float > const & >(( bp::arg("v") )) );
        { //::CEGUI::Size< float >::clamp
        
            typedef CEGUI::Size< float > exported_class_t;
            typedef void ( exported_class_t::*clamp_function_type )( ::CEGUI::Size< float >,::CEGUI::Size< float > ) ;
            
            Sizef_exposer.def( 
                "clamp"
                , clamp_function_type( &::CEGUI::Size< float >::clamp )
                , ( bp::arg("min"), bp::arg("max") ) );
        
        }
        Sizef_exposer.def( bp::self != bp::self );
        Sizef_exposer.def( bp::self * bp::other< float >() );
        Sizef_exposer.def( bp::self + bp::self );
        Sizef_exposer.def( bp::self == bp::self );
        { //::CEGUI::Size< float >::scaleToAspect
        
            typedef CEGUI::Size< float > exported_class_t;
            typedef void ( exported_class_t::*scaleToAspect_function_type )( ::CEGUI::AspectMode,float ) ;
            
            Sizef_exposer.def( 
                "scaleToAspect"
                , scaleToAspect_function_type( &::CEGUI::Size< float >::scaleToAspect )
                , ( bp::arg("mode"), bp::arg("ratio") ) );
        
        }
        Sizef_exposer.def_readwrite( "d_height", &CEGUI::Size< float >::d_height );
        Sizef_exposer.def_readwrite( "d_width", &CEGUI::Size< float >::d_width );
    }

}
