// This file has been generated by Py++.

#include "boost/python.hpp"
#include "indexing_suite/container_suite.hpp"
#include "indexing_suite/vector.hpp"
#include "python_CEGUI.h"
#include "StrIndexList.pypp.hpp"

namespace bp = boost::python;

void register_StrIndexList_class(){

    { //::std::vector< int >
        typedef bp::class_< std::vector< int > > StrIndexList_exposer_t;
        StrIndexList_exposer_t StrIndexList_exposer = StrIndexList_exposer_t( "StrIndexList" );
        bp::scope StrIndexList_scope( StrIndexList_exposer );
        StrIndexList_exposer.def( bp::indexing::vector_suite< std::vector< int > >() );
    }

}
