// This file has been generated by Py++.

#include "boost/python.hpp"
#include "python_CEGUI.h"
#include "UnifiedDim.pypp.hpp"

namespace bp = boost::python;

void register_UnifiedDim_class(){

    { //::CEGUI::UnifiedDim
        typedef bp::class_< CEGUI::UnifiedDim, bp::bases< CEGUI::BaseDim > > UnifiedDim_exposer_t;
        UnifiedDim_exposer_t UnifiedDim_exposer = UnifiedDim_exposer_t( "UnifiedDim", "*!\n\
        \n\
            Dimension type that represents an Unified dimension.  Implements BaseDim interface.\n\
        *\n", bp::init< CEGUI::UDim const &, CEGUI::DimensionType >(( bp::arg("value"), bp::arg("dim") ), "*!\n\
                \n\
                    Constructor.\n\
        \n\
                @param value\n\
                    UDim holding the value to assign to this UnifiedDim.\n\
        \n\
                @param dim\n\
                    DimensionType value indicating what this UnifiedDim is to represent.  This is required\n\
                    because we need to know what part of the base Window that the UDim scale component is\n\
                    to operate against.\n\
                *\n") );
        bp::scope UnifiedDim_scope( UnifiedDim_exposer );
    }

}
